export const CHANGE_RESULT_ADVISORY_FEEDBACK="CHANGE_RESULT_ADVISORY_FEEDBACK";
export const USER_LOADDING_RESULT = "USER_LOADDING_RESULT";
export const USER_LOADDING_RESULT_SUCCESS = "USER_LOADDING_RESULT_SUCCESS";
export const USER_LOADDING_RESULT_FAILD = "USER_LOADDING_RESULT_FAILD";