export const FETCH_LIST_PATIENTS = "FETCH_LIST_PATIENTS";
export const FETCH_LIST_PATIENTS_FAILD = "FETCH_LIST_PATIENTS_FAILD";

export const FETCH_LIST_PATIENTS_SUCCESS = "FETCH_LIST_PATIENTS_SUCCESS";
