export const FETCH_GROUP_TEST = "FETCH_GROUP_TEST";
export const FETCH_GROUP_TEST_SUCCESS = "FETCH_GROUP_TEST_SUCCESS";
export const FETCH_GROUP_TEST_FAILD = "FETCH_GROUP_TEST_FAILD";

export const SELECT_PAPER_TEST = "SELECT_PAPER_TEST";

