export const MOBILE_MENU_TOGGLE = "MOBILE_MENU_TOGGLE";
export const CHANGE_THEME = "CHANGE_THEME";
export const FETCH_LIST_NEWS = "FETCH_LIST_NEWS";
export const FETCH_LIST_NEWS_SUCCESS = "FETCH_LIST_NEWS_SUCCESS";
export const FETCH_LIST_NEWS_FAILD = "FETCH_LIST_NEWS_FAILD";

