export const USER_LOGIN ="USER_LOGIN";
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILD ="USER_LOGIN_FAILD";
export const USER_LOGIN_RESET ="USER_LOGIN_RESET";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_LOADDING_RESULT = "USER_LOADDING_RESULT";
export const USER_LOADDING_RESULT_SUCCESS = "USER_LOADDING_RESULT_SUCCESS";
export const USER_LOADDING_RESULT_FAILD = "USER_LOADDING_RESULT_FAILD";

